version: '3.9'

services:
  auxiliarcontabil.api:
    image: auxiliarcontabil.api
    build:
      context: .
      dockerfile: AuxiliarContabil.API/Dockerfile
    container_name: api-auxiliar-contabil
    networks:
      - rede-vps
    ports:
      - "5000:8080"
    environment:
      - MSSQL_CONNECTION_STRING=${MSSQL_CONNECTION_STRING}
networks:
  rede-vps:
    external: true
